---
sidebar: sidebar 
permalink: concept-aiq-digital-advisor.html 
keywords: concepts, active iq digital advisor, ontap 
summary: El asesor digital de Active IQ está integrado en la interfaz de usuario de BlueXP para que pueda optimizar las operaciones, la seguridad y el rendimiento de sus clústeres de ONTAP en una única consola. 
---
= Optimice los clústeres mediante Digital Advisor
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
https://www.netapp.com/services/support/active-iq/["Asesor digital"^] (Anteriormente Active IQ) está integrada en la interfaz de usuario de BlueXP para que pueda optimizar las operaciones, la seguridad y el rendimiento de sus clústeres de ONTAP en una única consola.



== Funciones

Puede ver el estado general de su sistema de almacenamiento, información de alto nivel sobre el estado del sistema, inventario, planificación, actualizaciones e información valiosa a nivel de lista de observación mediante Digital Advisor.

* Analice y optimice el estado de sus sistemas de almacenamiento
* Obtenga información sobre todos los riesgos de sus sistemas de almacenamiento y las acciones para mitigar los riesgos
* Analice el rendimiento de sus dispositivos de almacenamiento viendo el formato gráfico de los datos de rendimiento
* Obtenga información detallada acerca de los sistemas que han superado el 90 % de la capacidad o que están cerca del 90 %
* Obtenga información acerca del hardware y el software que han caducado o que están cerca de caducar en los próximos 6 meses
* Actualice el software de su sistema de almacenamiento y actualice el firmware de ONTAP con Ansible




== Sistemas ONTAP compatibles

El asesor digital proporciona información sobre todos los sistemas ONTAP y sistemas Cloud Volumes ONTAP locales de su cuenta de NSS.



== Cómo funciona el Asesor Digital con BlueXP

Consulte https://docs.netapp.com/us-en/active-iq/digital-advisor-integration-with-bluexp.html["Documentación de Digital Advisor"^] para obtener más detalles.
